name: Build and Push Docker image

on:
  push:
    tags:
      - "*"
    branches:
      - main
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "cmd.sh"

jobs:
  build-push-docker:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set short
        run: echo "short=${GITHUB_REF##*/}" >> "${GITHUB_ENV}"

      - name: Set tag
        run: echo "tag=${short/master/latest}" >> "${GITHUB_ENV}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            kitos9112/github-action-molecule:${{ env.tag }}
            ghcr.io/kitos9112/github-action-molecule:${{ env.tag }}
